diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Git/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.fsmonitor=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=bupohongchen
user.email=1017519453@qq.com
lfs.concurrenttransfers=3
lfs.customtransfer.xet.path=git-xet
lfs.customtransfer.xet.args=transfer
lfs.customtransfer.xet.concurrent=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:tapowanliwuyun/web_da-gs.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
